[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.11.2"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.38.2"

[prune]
  go-tests = true
  unused-packages = true
