[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.30"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.33.0"

[prune]
  go-tests = true
  unused-packages = true
